---
- name: installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:
  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
  - name: install metricbeat deb
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb
  - name: drop in metricbeat.yml
    copy:
      src: ./metricbeat.yml
      dest: /etc/metricbeat/
  - name: enable and configure docker module
    command: metricbeat modules enable docker
  - name: setup metricbeat
    command: metricbeat setup
  - name: start metricbeat service
    command: service metricbeat start
